package uk.gov.scotland.afrc.applications.model.domain;

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Embedded;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import uk.gov.scotland.afrc.applications.model.base.BaseTable;
import uk.gov.scotland.afrc.applications.model.base.BaseTableAware;
import uk.gov.scotland.afrc.applications.model.base.BaseTableListener;

/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator
 */

@Entity
@Table(name = "ENTITLEMENT_ROUTE")
@EntityListeners(BaseTableListener.class)
@NamedQueries(
	    value = {
	            @NamedQuery(
	                name = "EntitlementRoute.findAll",
	                query = "SELECT d FROM EntitlementRouteDBO d ORDER BY d.businessPriority") })
public class EntitlementRouteDBO implements Serializable, BaseTableAware {
    private static final long serialVersionUID = 1L;

    @Embedded
    private BaseTable baseTable;
    
	@Basic
	@Column(name="BUSINESS_PRIORITY", length=10)
	private Long businessPriority;

	@Id
	@Column(length=38)
	private long code;

	@Basic
	@Column(name="DEFAULT_CHOICE", length=1)
	private Boolean defaultChoice;

	@Basic
	@Column(nullable=false, length=100)
	private String description;

	@Basic
	@Column(name="END_DATE", columnDefinition="DATE")
	private Date endDate;

	@OneToMany(targetEntity=EntitlementCatgDBO.class, mappedBy="entitlementRoute", cascade=CascadeType.MERGE)
	private Set<EntitlementCatgDBO> entitlementCatgs = new HashSet<EntitlementCatgDBO>();

	@Basic
	@Column(nullable=false, length=20)
	private String name;

    @Column(name = "IS_MUTUALLY_EXCLUSIVE_FLAG")
    private Boolean isMutuallyExclusiveFlag;

	public EntitlementRouteDBO() {
	}

	public EntitlementRouteDBO(long code) {
		this.code = code;
	}

	public Long getBusinessPriority() {
		return businessPriority;
	}

	public void setBusinessPriority(Long businessPriority) {
		this.businessPriority = businessPriority;
	}

	public long getCode() {
		return code;
	}

	public void setCode(long code) {
		this.code = code;
	}

	public Boolean isDefaultChoice() {
		return defaultChoice;
	}

	public void setDefaultChoice(Boolean defaultChoice) {
		this.defaultChoice = defaultChoice;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Date getEndDate() {
		return endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public Set<EntitlementCatgDBO> getEntitlementCatgs() {
		return entitlementCatgs;
	}

	public void setEntitlementCatgs(Set<EntitlementCatgDBO> entitlementCatgs) {
		this.entitlementCatgs = entitlementCatgs;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}
	
    public Boolean getIsMutuallyExclusiveFlag() {
		return isMutuallyExclusiveFlag;
	}

	public void setIsMutuallyExclusiveFlag(Boolean isMutuallyExclusiveFlag) {
		this.isMutuallyExclusiveFlag = isMutuallyExclusiveFlag;
	}

	public BaseTable getBaseTable() {
        if (baseTable == null) {
            baseTable = new BaseTable();
        }

        return baseTable;
    }

    public void setBaseTable(BaseTable baseTable) {
        this.baseTable = baseTable;
    }
}